version: "3.7"

services:

  angular:
    container_name: weather_pokemon_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app